name: ArlightCore
version: '1.5.0'
main: com.arlight.core.ArlightCorePlugin
api-version: '1.21'
author: Arlight
description: Nucleo compartido para minijuegos, minipase, perfiles, estadísticas y sesiones

commands:
  core:
    description: Comando principal de ArlightCore
    usage: /core <items|reward|xp|setlobby|lobby|leaderboard|hologram|reload>
    permission: arlightcore.use

permissions:
  arlightcore.use:
    description: Permite usar el comando /core
    default: true
  arlightcore.admin:
    description: Permite administrar recompensas, XP, clasificaciones y hologramas
    default: op
  arlightcore.lobby.build:
    description: Permite construir manualmente dentro del lobby protegido
    default: op
